In [ ]:
##Create a numpy array


In [1]:
import numpy as np  # Import NumPy and alias it as 'np'

# Define your list
my_list = [1, 2, 3]

# Create a NumPy array from the list using 'np' alias
array1 = np.array(my_list)

# Print the NumPy array
print(array1)


[1 2 3]


In [ ]:
##Multi dimensional array

In [9]:
b=np.array([[1,2,3],[3,4,5]])

In [10]:
print(b)

[[1 2 3]
 [3 4 5]]


In [12]:
b.shape  ##Rows by column

(2, 3)

In [14]:
array1.shape


(3,)

In [15]:
b.dtype

dtype('int32')

In [16]:
b.ndim ## Number of rows

2

In [17]:
print(type(array1))

<class 'numpy.ndarray'>


In [19]:
np.arange(100)  ## returns values from zero to 99

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [22]:
c=range(10000)

In [23]:
%timeit [i**3 for i in c]

3.97 ms ± 499 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [25]:
c_numpy=np.arange(10000)
%timeit c_numpy

90.7 ns ± 13.7 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)


In [26]:
d=np.arange(12)

In [27]:
print(d)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [28]:
e=np.arange(2,20)
print(e)

[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [32]:
e1=np.arange(1,10,2)
print(e1)

[1 3 5 7 9]


In [33]:
print(np.zeros((3,2)))

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [34]:
print(np.ones((2,5)))

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [35]:
print(np.eye(3)) ## creating an identity matrix

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [36]:
print(np.full((3,3),2))

[[2 2 2]
 [2 2 2]
 [2 2 2]]


In [37]:
print(np.full((3,3),4.5))

[[4.5 4.5 4.5]
 [4.5 4.5 4.5]
 [4.5 4.5 4.5]]


In [42]:
ax=np.full((3,3),4.5, dtype= int)
print(ax) ## used to chop the values to only integers

[[4 4 4]
 [4 4 4]
 [4 4 4]]


In [43]:
print(np.diag([1,2,3,4,5]))

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [44]:
am=np.tile(ax,(3,1))

In [45]:
print(am)

[[4 4 4]
 [4 4 4]
 [4 4 4]
 [4 4 4]
 [4 4 4]
 [4 4 4]
 [4 4 4]
 [4 4 4]
 [4 4 4]]


In [47]:
## ranndom value
print(np.random.random())

0.3031104003775765


In [51]:
## Random values in a range
ami= 50*np.random.random() +2
print(ami)

13.047939846582516


In [52]:
randomarray=np.random.random([3,3])

In [53]:
print(randomarray)

[[0.85263806 0.96216678 0.29673688]
 [0.71194492 0.19321906 0.3867044 ]
 [0.97031285 0.19205564 0.15205532]]
